# -*- coding: utf-8 -*-
"""Assistente virtual freudiano

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIjCX939e6TkeUlrxpVBAUQexHe9Eyh6
"""

!pip -q install -U pip
!pip -q install -U "click>=8.2.1"
!pip -q install pdfplumber openai
!pip -q install git+https://github.com/openai/whisper.git
!pip -q install edge-tts
!apt-get -y install ffmpeg

"""# 1. Montar o Google Drive para acessar os PDFs 📂"""

from google.colab import drive
drive.mount('/content/drive')

"""
# 2. Localizar e filtrar PDFs das obras de Freud 📖"""

import os, re
import pdfplumber

pdf_path = "/content/drive/MyDrive/"  # seus PDFs do Freud estão na raiz do MyDrive, conforme sua listagem

# Lista PDFs na pasta
all_pdfs = [f for f in os.listdir(pdf_path) if f.lower().endswith(".pdf")]

# Filtro por nome (ajuste as palavras-chave se quiser)
pattern = r"freud|obras completas|imago|histeria|sonhos|psicanal"
freud_pdfs = [f for f in all_pdfs if re.search(pattern, f.lower())]

print("\nQtd PDFs na pasta:", len(all_pdfs))
print("Qtd PDFs do Freud (filtrados):", len(freud_pdfs))
print("Exemplos (até 10):", freud_pdfs[:10])

if len(freud_pdfs) == 0:
    raise FileNotFoundError(
        "Não encontrei PDFs do Freud com o filtro atual. "
        "Ajuste o 'pattern' ou mova seus PDFs para uma pasta específica e atualize pdf_path."
    )

"""# 3. Extrair texto dos PDFs (corpus)"""

corpus_parts = []
total_pages = 0
pages_with_text = 0

# Ajuste para testes: limite de páginas (None = tudo)
MAX_PAGES = 200  # ex.: 200 para teste

for fname in sorted(freud_pdfs):
    full = os.path.join(pdf_path, fname)
    try:
        with pdfplumber.open(full) as pdf:
            for page in pdf.pages:
                total_pages += 1
                text = page.extract_text()
                if text and text.strip():
                    pages_with_text += 1
                    corpus_parts.append(text)

                if MAX_PAGES is not None and total_pages >= MAX_PAGES:
                    break
    except Exception as e:
        print(f"[AVISO] Falha ao ler {fname}: {e}")

    if MAX_PAGES is not None and total_pages >= MAX_PAGES:
        break

corpus = "\n".join(corpus_parts)

print("\n--- Corpus ---")
print("Páginas lidas:", total_pages)
print("Páginas com texto extraído:", pages_with_text)
print("Tamanho do corpus (chars):", len(corpus))

if pages_with_text == 0:
    print("\n[ATENÇÃO] Nenhuma página retornou texto com pdfplumber.")
    print("Isso normalmente significa PDF escaneado (imagem). Nesse caso você precisará OCR (pytesseract).")

"""# 4. Gravação de áudio 🎤"""

from IPython.display import HTML, display
from google.colab import output
from base64 import b64decode
import uuid, os

_last_audio_path = None

def _save_audio_js(data_url, out_webm="/content/request_audio.webm"):
    global _last_audio_path
    audio_bytes = b64decode(data_url.split(",")[1])
    with open(out_webm, "wb") as f:
        f.write(audio_bytes)
    _last_audio_path = out_webm
    return "OK"

cb_name = f"rec_{uuid.uuid4().hex}"
output.register_callback(cb_name, _save_audio_js)

display(HTML(f"""
<div style="display:flex; gap:12px; align-items:center;">
  <button id="startBtn" style="padding:10px 14px;">🎙️ Gravar</button>
  <button id="stopBtn" style="padding:10px 14px;" disabled>⏹️ Parar</button>
  <span id="status" style="font-family:monospace;">Pronto.</span>
</div>

<script>
let stream, recorder, chunks;

const startBtn = document.getElementById("startBtn");
const stopBtn  = document.getElementById("stopBtn");
const statusEl = document.getElementById("status");

function blobToDataURL(blob) {{
  return new Promise((resolve) => {{
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.readAsDataURL(blob);
  }});
}}

startBtn.onclick = async () => {{
  try {{
    statusEl.textContent = "Pedindo permissão do microfone...";
    stream = await navigator.mediaDevices.getUserMedia({{ audio: true }});
    recorder = new MediaRecorder(stream);
    chunks = [];

    recorder.ondataavailable = e => chunks.push(e.data);
    recorder.onstart = () => {{
      statusEl.textContent = "Gravando... (clique em Parar)";
      startBtn.disabled = true;
      stopBtn.disabled = false;
    }};
    recorder.onstop = async () => {{
      statusEl.textContent = "Processando áudio...";
      const blob = new Blob(chunks, {{ type: recorder.mimeType }});
      const dataUrl = await blobToDataURL(blob);

      await google.colab.kernel.invokeFunction("{cb_name}", [dataUrl], {{}});
      statusEl.textContent = "Áudio enviado. Rode a próxima célula.";

      stopBtn.disabled = true;
      startBtn.disabled = false;
      stream.getTracks().forEach(t => t.stop());
    }};

    recorder.start();
  }} catch (e) {{
    statusEl.textContent = "Erro ao acessar microfone: " + e;
    startBtn.disabled = false;
    stopBtn.disabled = true;
  }}
}};

stopBtn.onclick = () => {{
  if (recorder && recorder.state === "recording") recorder.stop();
}};
</script>
"""))

"""# 5. Transcrição com Whisper 🧠"""

import whisper
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print("\nGPU disponível?", torch.cuda.is_available(), "| device:", device)

model = whisper.load_model("small").to(device)

result = model.transcribe(
    record_file,
    fp16=(device == "cuda"),
    language="pt"
)

transcription = result["text"].strip()
print("\nTranscrição:", transcription)

"""# 6. OpenAI (SDK atual) + resposta 💬"""

import os
os.environ["OPENAI_API_KEY"] = "SUA CHAVE AQUI"
import os
from openai import OpenAI
import re

# 🔐 Pegar chave da variável de ambiente
api_key = os.environ.get("OPENAI_API_KEY", "").strip()

# ❗ Verificação de segurança
if not api_key:
    raise ValueError(
        "OPENAI_API_KEY não encontrada.\n"
        "Defina a variável com:\n"
        "os.environ['OPENAI_API_KEY'] = 'SUA_CHAVE'\n"
        "ou use o Secrets do Colab."
    )

# 🔑 Criar cliente
client = OpenAI(api_key=api_key)

# Seleção simples de contexto (heurística) para não mandar corpus aleatório
def pick_context_simple(corpus_text: str, query: str, max_chars=6000):
    words = re.findall(r"\w+", query.lower())
    if not words:
        return corpus_text[:2000]

    hits = []
    current_len = 0

    # usa até 12 palavras mais informativas (aproximação simples)
    key_words = [w for w in words if len(w) >= 4][:12]

    for line in corpus_text.split("\n"):
        low = line.lower()
        score = sum(1 for w in key_words if w in low)
        if score >= 2:
            hits.append(line)
            current_len += len(line) + 1
            if current_len >= max_chars:
                break

    if hits:
        return "\n".join(hits)[:max_chars]

    return corpus_text[:2000]

contexto = pick_context_simple(corpus, transcription, max_chars=6000)

resp = client.responses.create(
    model="gpt-4.1-mini",
    input=[
        {
            "role": "system",
            "content": (
                "Você é um analista virtual inspirado em Freud. "
                "Use conceitos psicanalíticos freudianos e linguagem clara, útil e cuidadosa. "
                "Faça perguntas complementares quando necessário. "
                "Não invente citações com páginas; use referências gerais ao corpus quando fizer sentido."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Pergunta (transcrição do áudio): {transcription}\n\n"
                f"Trechos do corpus freudiano (para apoio):\n{contexto}"
            ),
        },
    ],
)

chatgpt_response = resp.output_text.strip()
print("\nResposta:\n", chatgpt_response)

"""# 6. Síntese de voz com edge-TTS 🔊"""

import edge_tts
from IPython.display import Audio, display

async def tts_edge(text, out_mp3="/content/response_audio.mp3", voice="pt-BR-FranciscaNeural"):
    communicate = edge_tts.Communicate(text=text, voice=voice)
    await communicate.save(out_mp3)
    return out_mp3

response_audio = await tts_edge(chatgpt_response)  # ✅ aqui é await, não asyncio.run
display(Audio(response_audio, autoplay=True))
